// constants (actions)
export const VERSION = {
	current: "1.0"
};

const p = "conlangs-toolbox/reducer/";
export const CHANGE_THEME = p+"CHANGE_THEME";
export const TOGGLE_DISABLE_CONFIRM = p+"TOGGLE_DISABLE_CONFIRM";
export const ADD_CATEGORY = p+"ADD_CATEGORY";
export const START_EDIT_CATEGORY = p+"START_EDIT_CATEGORY";
export const CANCEL_EDIT_CATEGORY = p+"CANCEL_EDIT_CATEGORY";
export const DO_EDIT_CATEGORY = p+"DO_EDIT_CATEGORY";
export const DELETE_CATEGORY = p+"DELETE_CATEGORY";
export const TOGGLE_SYLLABLES = p+"TOGGLE_SYLLABLES";
export const EDIT_SYLLABLES = p+"EDIT_SYLLABLES";
export const ADD_REWRITE_RULE = p+"ADD_REWRITE_RULE";
export const START_EDIT_REWRITE_RULE = p+"START_EDIT_REWRITE_RULE";
export const CANCEL_EDIT_REWRITE_RULE = p+"CANCEL_EDIT_REWRITE_RULE";
export const DO_EDIT_REWRITE_RULE = p+"DO_EDIT_REWRITE_RULE";
export const DELETE_REWRITE_RULE = p+"DELETE_REWRITE_RULE";
export const REORDER_REWRITE_RULE = p+"REORDER_REWRITE_RULE";
export const SET_MONO_RATE = p+"SET_MONO_RATE";
export const SET_MAX_SYLLABLES = p+"SET_MAX_SYLLABLES";
export const SET_CATEGORY_DROPOFF = p+"SET_CATEGORY_DROPOFF";
export const SET_SYLLABLE_DROPOFF = p+"SET_SYLLABLE_DROPOFF";
export const SET_OUTPUT = p+"SET_OUTPUT";
export const SET_SYLLABLE_BREAKS = p+"SET_SYLLABLE_BREAKS";
export const SET_NUMBER_OF_SENTENCES = p+"SET_NUMBER_OF_SENTENCES";
export const SET_SENTENCE_CAPITALIZATION = p+"SET_SENTENCE_CAPITALIZATION";
export const SET_DECLARATIVE_PRE = p+"SET_DECLARATIVE_PRE";
export const SET_DECLARATIVE_POST = p+"SET_DECLARATIVE_POST";
export const SET_INTERROGATIVE_PRE = p+"SET_INTERROGATIVE_PRE";
export const SET_INTERROGATIVE_POST = p+"SET_INTERROGATIVE_POST";
export const SET_EXCLAMATORY_PRE = p+"SET_EXCLAMATORY_PRE";
export const SET_EXCLAMATORY_POST = p+"SET_EXCLAMATORY_POST";
export const SET_WORD_CAPITALIZATION = p+"SET_WORD_CAPITALIZATION";
export const SET_SORT_WORDLIST = p+"SET_SORT_WORDLIST";
export const SET_WORDLIST_MULTICOLUMN = p+"SET_WORDLIST_MULTICOLUMN";
export const SET_WORDS_PER_WORDLIST = p+"SET_WORDS_PER_WORDLIST";
export const SET_CUSTOM_INFO = p+"SET_CUSTOM_INFO";
export const TOGGLE_MODAL = p+"TOGGLE_MODAL";
export const LOAD_PRESET = p+"LOAD_PRESET";
export const CLEAR_EVERYTHING_WG = p+"CLEAR_EVERYTHING_WG";
export const OVERWRITE_STATE = p+"OVERWRITE_STATE";
export const LOAD_CUSTOM_INFO = p+"LOAD_CUSTOM_INFO";
export const CHANGE_VIEW = p+"CHANGE_VIEW";
