// constants (actions)
export const VERSION = {
	current: "1.0"
};

const p = "conlangs-toolbox/reducer/";
export const CHANGE_THEME = p+"CHANGE_THEME";
export const TOGGLE_DISABLE_CONFIRM = p+"TOGGLE_DISABLE_CONFIRM";

export const ADD_CATEGORY_WG = p+"ADD_CATEGORY_WG";
export const START_EDIT_CATEGORY_WG = p+"START_EDIT_CATEGORY_WG";
export const CANCEL_EDIT_CATEGORY_WG = p+"CANCEL_EDIT_CATEGORY_WG";
export const DO_EDIT_CATEGORY_WG = p+"DO_EDIT_CATEGORY_WG";
export const DELETE_CATEGORY_WG = p+"DELETE_CATEGORY_WG";

export const TOGGLE_SYLLABLES = p+"TOGGLE_SYLLABLES";
export const EDIT_SYLLABLES = p+"EDIT_SYLLABLES";

export const ADD_REWRITE_RULE_WG = p+"ADD_REWRITE_RULE_WG";
export const START_EDIT_REWRITE_RULE_WG = p+"START_EDIT_REWRITE_RULE_WG";
export const CANCEL_EDIT_REWRITE_RULE_WG = p+"CANCEL_EDIT_REWRITE_RULE_WG";
export const DO_EDIT_REWRITE_RULE_WG = p+"DO_EDIT_REWRITE_RULE_WG";
export const DELETE_REWRITE_RULE_WG = p+"DELETE_REWRITE_RULE_WG";
export const REORDER_REWRITE_RULE_WG = p+"REORDER_REWRITE_RULE_WG";

export const SET_MONO_RATE_WG = p+"SET_MONO_RATE";
export const SET_MAX_SYLLABLES_WG = p+"SET_MAX_SYLLABLES";
export const SET_CATEGORY_DROPOFF_WG = p+"SET_CATEGORY_DROPOFF";
export const SET_SYLLABLE_DROPOFF_WG = p+"SET_SYLLABLE_DROPOFF";
export const SET_OUTPUT_WG = p+"SET_OUTPUT";
export const SET_SYLLABLE_BREAKS_WG = p+"SET_SYLLABLE_BREAKS";
export const SET_NUMBER_OF_SENTENCES_WG = p+"SET_NUMBER_OF_SENTENCES";
export const SET_SENTENCE_CAPITALIZATION_WG = p+"SET_SENTENCE_CAPITALIZATION";
export const SET_DECLARATIVE_PRE_WG = p+"SET_DECLARATIVE_PRE";
export const SET_DECLARATIVE_POST_WG = p+"SET_DECLARATIVE_POST";
export const SET_INTERROGATIVE_PRE_WG = p+"SET_INTERROGATIVE_PRE";
export const SET_INTERROGATIVE_POST_WG = p+"SET_INTERROGATIVE_POST";
export const SET_EXCLAMATORY_PRE_WG = p+"SET_EXCLAMATORY_PRE";
export const SET_EXCLAMATORY_POST_WG = p+"SET_EXCLAMATORY_POST";
export const SET_WORD_CAPITALIZATION_WG = p+"SET_WORD_CAPITALIZATION";
export const SET_SORT_WORDLIST_WG = p+"SET_SORT_WORDLIST";
export const SET_WORDLIST_MULTICOLUMN_WG = p+"SET_WORDLIST_MULTICOLUMN";
export const SET_WORDS_PER_WORDLIST_WG = p+"SET_WORDS_PER_WORDLIST";
export const SET_CUSTOM_INFO_WG = p+"SET_CUSTOM_INFO_WG";

export const ADD_CATEGORY_WE = p+"ADD_CATEGORY_WE";
export const START_EDIT_CATEGORY_WE = p+"START_EDIT_CATEGORY_WE";
export const CANCEL_EDIT_CATEGORY_WE = p+"CANCEL_EDIT_CATEGORY_WE";
export const DO_EDIT_CATEGORY_WE = p+"DO_EDIT_CATEGORY_WE";
export const DELETE_CATEGORY_WE = p+"DELETE_CATEGORY_WE";

export const ADD_TRANSFORM_WE = p+"ADD_TRANSFORM_WE";
export const START_EDIT_TRANSFORM_WE = p+"START_EDIT_TRANSFORM_WE";
export const CANCEL_EDIT_TRANSFORM_WE = p+"CANCEL_EDIT_TRANSFORM_WE";
export const DO_EDIT_TRANSFORM_WE = p+"DO_EDIT_TRANSFORM_WE";
export const DELETE_TRANSFORM_WE = p+"DELETE_TRANSFORM_WE";
export const REORDER_TRANSFORM_WE = p+"REORDER_TRANSFORM_WE";

export const TOGGLE_MODAL = p+"TOGGLE_MODAL";
export const LOAD_PRESET_WG = p+"LOAD_PRESET";
export const CLEAR_EVERYTHING_WG = p+"CLEAR_EVERYTHING_WG";
export const OVERWRITE_STATE = p+"OVERWRITE_STATE";
export const LOAD_CUSTOM_INFO_WG = p+"LOAD_CUSTOM_INFO_WG";

export const CHANGE_VIEW = p+"CHANGE_VIEW";
